name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend-hemicycle/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend-hemicycle/**'

defaults:
  run:
    working-directory: backend-hemicycle

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: backend-hemicycle/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test